source 'https://rubygems.org'

ruby '2.2.2'

gem 'rails',                                                                    '4.2.1'
gem 'responders'
gem 'sqlite3'
gem 'sass-rails'
gem 'slim-rails'
gem 'kaminari'
gem "mini_magick"
gem 'carrierwave'
gem 'uglifier'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'jbuilder'
gem 'bcrypt'
gem 'sorcery'
gem 'ransack',      github: 'activerecord-hackery/ransack', branch: 'rails-4.2'
gem 'foundation-rails'
gem 'foundation-icons-sass-rails'
gem 'momentjs-rails'
# gem 'cocoon'
# gem 'scrollreveal-rails'
# gem 'visualsearch-rails'
# gem 'text_to_color-rails'
# gem 'polymer-rails'
# gem 'polymer-core-rails'
# gem 'polymer-paper-rails'
gem 'bootstrap-datepicker-rails'
gem 'local_time'
gem 'simple_form'
gem 'country_select'
gem 'i18n-country-translations'
gem 'combined_time_select'
gem 'exception_handler'
# Problem Ember.js with 'sprockets' '>= 3.0.0', only '2.12.3'
gem 'sprockets',                                                                '2.12.3'
gem 'sprockets-rails'
gem 'friendly_id'
gem 'puma'
gem 'lograge'
gem 'logstash-event'
gem 'ember-rails'
gem 'ember-source'

group :development do
  gem 'spring'
  gem 'pry-rails'
  gem 'looksee'
  gem 'awesome_print'
  gem 'hirb'
  gem 'rails_layout'
  gem 'web-console'
  gem 'binding_of_caller'
  gem 'quiet_assets'
end
