source 'https://rubygems.org'

ruby '2.2.1'

gem 'rails',                                                                    '4.2.1'
gem 'sqlite3'
gem 'sass-rails',                                                               '~> 5.0.3'
gem 'slim-rails',                                                               '~> 3.0.1'
gem 'kaminari'
gem "mini_magick"
gem 'carrierwave'
gem 'uglifier'
gem 'therubyracer', platforms: :ruby
gem 'jquery-rails'
gem 'jbuilder'
gem 'bcrypt'
gem 'sorcery'
gem 'ransack',      github: 'activerecord-hackery/ransack', branch: 'rails-4.2'
gem 'foundation-rails',                                                         '~> 5.5.2.1'
gem 'foundation-icons-sass-rails',                                              '~> 3.0.0'
gem 'momentjs-rails'
# gem 'cocoon'
# gem 'scrollreveal-rails'
# gem 'visualsearch-rails'
# gem 'text_to_color-rails'
# gem 'polymer-rails'
# gem 'polymer-core-rails'
# gem 'polymer-paper-rails'
gem 'bootstrap-datepicker-rails'
gem 'local_time'
gem 'simple_form'
gem 'country_select'
gem 'i18n-country-translations'
gem 'combined_time_select',                                                     '~> 1.0.1'
gem 'exception_handler',                                                        '~> 0.3.45'
# Problem this gem don't work ember.js
# gem 'sprockets', '3.0.0' '3.0.1'
gem 'sprockets',                                                                '2.12.3'
gem 'sprockets-rails',                                                          '~> 2.3.0'
gem 'friendly_id',                                                              '~> 5.1.0'
gem 'puma',                                                                     '~> 2.11.2'
gem 'lograge',                                                                  '~> 0.3.1'
gem 'logstash-event',                                                           '~> 1.2.02'
gem 'ember-rails',                                                              '~> 0.18.2'
gem 'ember-source',                                                             '~> 1.11.3.1'

group :development do
  gem 'spring'
  gem 'pry-rails'
  gem 'looksee'
  gem 'awesome_print'
  gem 'hirb'
  gem 'rails_layout'
  gem 'web-console',                                                            '~> 2.1.2'
  gem 'binding_of_caller',                                                      '~> 0.7.3.pre1'
  gem 'quiet_assets',                                                           '~> 1.1.0'
end
